apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    service: dispatch
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
  - name: http
    port: 55555   # The service port
    targetPort: 55555  # The container's port
    nodePort: 30055  # Custom NodePort (Optional, Kubernetes assigns if omitted)
  selector:
    service: dispatch
